/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE habitsBaseService PLEASE EDIT ../habits.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Habits } from '../../domain/habits_db/habits';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Habits.service.ts
 */

/*
 * SCHEMA DB Habits
 *
	{
		Description: {
			type: 'String'
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class HabitsBaseService {

    private habitsCollection: AngularFirestoreCollection<Habits>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.habitsCollection = afs.collection<Habits>('habits');
    }


    // CRUD METHODS

    /**
    * HabitsService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Habits): Promise<DocumentReference> {
        return this.habitsCollection.add(item);
    }

    /**
    * HabitsService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.habitsCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * HabitsService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): AngularFirestoreDocument<Habits> {
        return this.afs.doc<Habits>('habits/' + id);
    }

    /**
    * HabitsService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Habits[]> {
        return this.afs.collection('habits').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Habits;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * HabitsService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Habits>, item: Habits): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
